Config/urls.py
from django.contrib import admin
from django.urls import path, include
from GraphQL.views import GraphQLPlaygroundView
from django.views.decorators.csrf import csrf_exempt
from graphene_file_upload.django import FileUploadGraphQLView
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.conf import settings
import debug_toolbar

# from Nady_System.views import helth


urlpatterns = [
    path("entity/", include("django_spaghetti.urls")),
    path(
        "graphql",
        csrf_exempt(
            FileUploadGraphQLView.as_view(
                graphiql=False,
            )
        ),
    ),
    path(
        "playground",
        csrf_exempt(GraphQLPlaygroundView.as_view(endpoint="/graphql")),
    ),
    path("__debug__/", include(debug_toolbar.urls)),
    path("i18n/", include("django.conf.urls.i18n")),
]


urlpatterns += i18n_patterns(
    path("", include("Nady_System.urls")),
    path("accounts/", include("allauth.urls")),
    path("admin/", admin.site.urls),
    # path("accounts/", include("django.contrib.auth.urls")),
    # path("accounts/", include("Person.urls", namespace="accounts")),
    path("payment/", include("Payment.urls", namespace="payment")),
    path('currencies/', include('currencies.urls')),  # django-currencies
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Nady_System/urls.py
from django.urls import path
from .views import (
    home,
    about,
    services,
    appointment,
    gallery,
    team,
    blog,
    contact,
)

app_name = "Nady_System"

urlpatterns = [
    path("", home, name="home"),
    path("about/", about, name="about"),
    path("services/", services, name="services"),
    path("appointment/", appointment, name="appointment"),
    path("gallery/", gallery, name="gallery"),
    path("team/", team, name="team"),
    path("blog/", blog, name="blog"),
    path("contact/", contact, name="contact"),
]

templates/base.html
{% load static %} {% load i18n %} {% load currency %}

{# Load the tag library #} {% load bootstrap5 %} {# Load CSS and JavaScript #} {% bootstrap_css %} {% bootstrap_javascript %} {# Display django.contrib.messages as Bootstrap alerts #} {% bootstrap_messages %}
<!DOCTYPE html>
<html lang="en">
<!-- Basic -->

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" />

    <!-- Site Metas -->
    <title>Health Lab - Responsive HTML5 Template</title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <!-- Site Icons -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
    <link rel="apple-touch-icon" href="{% static 'images/apple-touch-icon.png' %}" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <!-- Pogo Slider CSS -->
    <link rel="stylesheet" href="{% static 'css/pogo-slider.min.css' %}" />
    <!-- Site CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}" />
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}" />

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body id="home" data-spy="scroll" data-target="#navbar-wd" data-offset="98">
    <!-- LOADER -->
    <div id="preloader">
        <div class="loader">
            <img src="{% static 'images/preloader.gif' %}" alt="preloader" />
        </div>
    </div>
    <!-- END LOADER -->

    <!-- Start header -->
    <header class="top-header">
        <nav class="navbar header-nav navbar-expand-lg">
            <div class="container">
                <a class="navbar-brand" href="{% url 'Nady_System:home' %}"><img src="{% static 'images/logo.png' %}" alt="image" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-wd" aria-controls="navbar-wd" aria-expanded="false" aria-label="Toggle navigation">
                    <span></span>
                    <span></span>
                    <span></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbar-wd">
                    <ul class="navbar-nav">
                        <li>
                            <a class="nav-link {% if request.resolver_match.view_name == 'Nady_System:home' %}active{% endif %}" href="{% url 'Nady_System:home' %}">Home</a>
                        </li>
                        <li>
                            <a class="nav-link {% if request.resolver_match.view_name == 'Nady_System:about' %}active{% endif %}" href="{% url 'Nady_System:about' %}">About Us</a>
                        </li>
                        <li>
                            <a class="nav-link {% if request.resolver_match.view_name == 'Nady_System:services' %}active{% endif %}" href="{% url 'Nady_System:services' %}">Services</a>
                        </li>
                        <li>
                            <a class="nav-link {% if request.resolver_match.view_name == 'Nady_System:appointment' %}active{% endif %}" href="{% url 'Nady_System:appointment' %}">Appointment</a>
                        </li>
                        <li>
                            <a class="nav-link {% if request.resolver_match.view_name == 'Nady_System:gallery' %}active{% endif %}" href="{% url 'Nady_System:gallery' %}">Gallery</a></a>
                        </li>
                        <li>
                            <a class="nav-link {% if request.resolver_match.view_name == 'Nady_System:team' %}active{% endif %}" href="{% url 'Nady_System:team' %}">Doctor</a>
                        </li>
                        <li>
                            <a class="nav-link {% if request.resolver_match.view_name == 'Nady_System:blog' %}active{% endif %}" href="{% url 'Nady_System:blog' %}">Blog</a>
                        </li>
                        <li>
                            <a class="nav-link {% if request.resolver_match.view_name == 'Nady_System:contact' %}active{% endif %}" href="{% url 'Nady_System:contact' %}">Contact</a>
                        </li>
                        <li>
                            <a class="nav-link {% if request.resolver_match.view_name == 'Payment:paypal' %}active{% endif %}" href="{% url 'Payment:paypal' %}">Paypal</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <!-- End header -->

    <!-- <h1 class="text-center">{{ request.resolver_match.view_name}}</h1>
    <h1 class="text-center">{{ request.resolver_match.url_name}}</h1> -->

    {% block Content %} {% endblock Content %}

    <!-- Start top bar -->
    <div class="main-top">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="left-top">
                        <a class="new-btn-d br-2" href="#"><span>Book Appointment</span></a>
                        <div class="mail-b">
                            <a href="#"><i class="fa fa-envelope-o" aria-hidden="true"></i>
                                demo@gmail.com</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="wel-nots">
                        <p>Welcome to Our Health Lab!</p>
                    </div>
                    <div class="right-top">
                        <ul>
                            <li>
                                <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-youtube-play" aria-hidden="true"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End top bar -->

    <!-- Start Footer -->
    <footer class="footer-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <p class="footer-company-name">
                        All Rights Reserved. &copy; 2018 <a href="#">Health Lab</a> Design By : <a href="https://html.design/">html design</a>
                    </p>
                </div>
            </div>
        </div>
    </footer>
    <!-- End Footer -->

    <!-- <a href="#" id="scroll-to-top" class="new-btn-d br-2"><i class="fa fa-angle-up"></i></a> -->

    <!-- ALL JS FILES -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- ALL PLUGINS -->
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/jquery.pogo-slider.min.js' %}"></script>
    <script src="{% static 'js/slider-index.js' %}"></script>
    <script src="{% static 'js/smoothscroll.js' %}"></script>
    <script src="{% static 'js/TweenMax.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/form-validator.min.js' %}"></script>
    <script src="{% static 'js/contact-form-script.js' %}"></script>
    <script src="{% static 'js/isotope.min.js' %}"></script>
    <script src="{% static 'js/images-loded.min.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>


    {% block Scripts %} {% endblock Scripts %}


</body>

</html>

templates/paypal0.html
{% extends 'base.html' %} {% block Content %}
<div id="smart-button-container">
    <div style="text-align: center">
        <label for="description">Desription </label
    ><input
      type="text"
      name="descriptionInput"
      id="description"
      maxlength="127"
      value=""
    />
  </div>
  <p
    id="descriptionError"
    style="visibility: hidden; color: red; text-align: center"
  >
    Please enter a description
  </p>
  <div style="text-align: center">
    <label for="amount">Amount </label
    ><input name="amountInput" type="number" id="amount" value="" /><span>
      USD</span
    >
  </div>
  <p
    id="priceLabelError"
    style="visibility: hidden; color: red; text-align: center"
  >
    Please enter a price
  </p>
  <div id="invoiceidDiv" style="text-align: center; display: none">
    <label for="invoiceid">Invoice ID </label
    ><input
      name="invoiceid"
      maxlength="127"
      type="text"
      id="invoiceid"
      value=""
    />
  </div>
  <p
    id="invoiceidError"
    style="visibility: hidden; color: red; text-align: center"
  >
    Please enter an Invoice ID
  </p>
  <div
    style="text-align: center; margin-top: 0.625rem"
    id="paypal-button-container"
  ></div>
</div>
{% endblock Content %} {% block Scripts %}
<script
  src="https://www.paypal.com/sdk/js?client-id=sb&enable-funding=venmo&currency=USD"
  data-sdk-integration-source="button-factory"
></script>
<script>
  function initPayPalButton() {
    var description = document.querySelector(
      "#smart-button-container #description"
    );
    var amount = document.querySelector("#smart-button-container #amount");
    var descriptionError = document.querySelector(
      "#smart-button-container #descriptionError"
    );
    var priceError = document.querySelector(
      "#smart-button-container #priceLabelError"
    );
    var invoiceid = document.querySelector(
      "#smart-button-container #invoiceid"
    );
    var invoiceidError = document.querySelector(
      "#smart-button-container #invoiceidError"
    );
    var invoiceidDiv = document.querySelector(
      "#smart-button-container #invoiceidDiv"
    );

    var elArr = [description, amount];

    if (invoiceidDiv.firstChild.innerHTML.length > 1) {
      invoiceidDiv.style.display = "block";
    }

    var purchase_units = [];
    purchase_units[0] = {};
    purchase_units[0].amount = {};

    function validate(event) {
      return event.value.length > 0;
    }

    paypal
      .Buttons({
        style: {
          color: "gold",
          shape: "pill",
          label: "paypal",
          layout: "vertical",
        },

        onInit: function (data, actions) {
          actions.disable();

          if (invoiceidDiv.style.display === "block") {
            elArr.push(invoiceid);
          }

          elArr.forEach(function (item) {
            item.addEventListener("keyup", function (event) {
              var result = elArr.every(validate);
              if (result) {
                actions.enable();
              } else {
                actions.disable();
              }
            });
          });
        },

        onClick: function () {
          if (description.value.length < 1) {
            descriptionError.style.visibility = "visible";
          } else {
            descriptionError.style.visibility = "hidden";
          }

          if (amount.value.length < 1) {
            priceError.style.visibility = "visible";
          } else {
            priceError.style.visibility = "hidden";
          }

          if (
            invoiceid.value.length < 1 &&
            invoiceidDiv.style.display === "block"
          ) {
            invoiceidError.style.visibility = "visible";
          } else {
            invoiceidError.style.visibility = "hidden";
          }

          purchase_units[0].description = description.value;
          purchase_units[0].amount.value = amount.value;

          if (invoiceid.value !== "") {
            purchase_units[0].invoice_id = invoiceid.value;
          }
        },

        createOrder: function (data, actions) {
          return actions.order.create({
            purchase_units: purchase_units,
          });
        },

        onApprove: function (data, actions) {
          return actions.order.capture().then(function (orderData) {
            // Full available details
            console.log(
              "Capture result",
              orderData,
              JSON.stringify(orderData, null, 2)
            );

            // Show a success message within this page, e.g.
            const element = document.getElementById("paypal-button-container");
            element.innerHTML = "";
            element.innerHTML = "<h3>Thank you for your payment!</h3>";

            // Or go to another URL:  actions.redirect('thank_you.html');
          });
        },

        onError: function (err) {
          console.log(err);
        },
      })
      .render("#paypal-button-container");
  }
  initPayPalButton();
</script>

{% endblock Scripts %}

templates/translate.html
{% load i18n %}

<form action="{% url 'set_language' %}" method="post">{% csrf_token %}
    <input name="next" type="hidden" value="{{ redirect_to }}">
    <select name="language">
        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% get_language_info_list for LANGUAGES as languages %}
        {% for language in languages %}
            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                {{ language.name_local }} ({{ language.code }})
            </option>
        {% endfor %}
    </select>
    <input type="submit" value="Go">
</form>